//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutas
    {
        public int IdRuta { get; set; }
        public string NombreRuta { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
