//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int IdVenta { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdRuta { get; set; }
        public Nullable<int> CantidadPersonas { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
